// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWZLzOILiGXmCmKZRGnPVNF4NzEvrM1kg',
    appId: '1:156598573308:web:f365bbe0a4a06f520fdf79',
    messagingSenderId: '156598573308',
    projectId: 'rotify-flutter-clone',
    authDomain: 'rotify-flutter-clone.firebaseapp.com',
    storageBucket: 'rotify-flutter-clone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxCCCI85PEZ5fienphWHh_aSY5V_YGY2Q',
    appId: '1:156598573308:android:558f00be8bdeb72e0fdf79',
    messagingSenderId: '156598573308',
    projectId: 'rotify-flutter-clone',
    storageBucket: 'rotify-flutter-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-ackoReg45CL-YAopiyovYeex1ZaY5Q',
    appId: '1:156598573308:ios:4aac97eed7339ab90fdf79',
    messagingSenderId: '156598573308',
    projectId: 'rotify-flutter-clone',
    storageBucket: 'rotify-flutter-clone.firebasestorage.app',
    iosBundleId: 'com.example.red',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk-ackoReg45CL-YAopiyovYeex1ZaY5Q',
    appId: '1:156598573308:ios:4aac97eed7339ab90fdf79',
    messagingSenderId: '156598573308',
    projectId: 'rotify-flutter-clone',
    storageBucket: 'rotify-flutter-clone.firebasestorage.app',
    iosBundleId: 'com.example.red',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWZLzOILiGXmCmKZRGnPVNF4NzEvrM1kg',
    appId: '1:156598573308:web:5afb98162689c9890fdf79',
    messagingSenderId: '156598573308',
    projectId: 'rotify-flutter-clone',
    authDomain: 'rotify-flutter-clone.firebaseapp.com',
    storageBucket: 'rotify-flutter-clone.firebasestorage.app',
  );
}
